color0 #221f32
color1 #fd4663
color2 #816fec
color3 #af5ed8
color4 #cc66bd
color5 #a093ec
color6 #cd96e9
color7 #f2f2f3
color8 #666473
color9 #fd4663
color10 #816fec
color11 #af5ed8
color12 #cc66bd
color13 #a093ec
color14 #cd96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #191826
background            #191826
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #221f32
active_border_color   #7a67e4
inactive_border_color #221f32
url_color             #7a67e4

active_tab_foreground   #0e0c19
active_tab_background   #7a67e4
inactive_tab_foreground #b0afb6
inactive_tab_background #221f32
cursor_trail_color      #b0afb6
